# Generated by Django 4.2 on 2023-05-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='lte_exists',
            field=models.CharField(default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
