# Generated by Django 4.2 on 2023-05-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_lte_exists_phone_release_date_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
